language: android
android:
  components:
  - build-tools-28.0.1
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
  - sys-img-armeabi-v7a-android-28
  - sys-img-armeabi-v7a-android-21
before_install:
- openssl aes-256-cbc -K $encrypted_a2267fbe3620_key -iv $encrypted_a2267fbe3620_iv
  -in ./app/google-services.json.enc -out ./app/google-services.json -d
- chmod +x gradlew
